### ISSUE TITLE
Reservations: Editing Placeholders?

### ISSUE THREAD

**Issue by bwhitworth** [nss-evening-cohort-11/nutshell-stormtroopers#36]
One of the branch reviews I did - I noticed that the pre-populated name, # guests, etc were just placeholders and not actually Values.  The one I did, I only changed the number of guests, and when I submitted, it removed the name of the party, because I didn't enter anything.  If this wasn't fixed in a later commit, needs to be looked at. Thanks!

**Comment by delindell** [comment]
Fixed this, good catch as always.
